file = open("ABC.txt", "w")
file.write("MyName")
file.close()
a = open("ABC.txt", "r")
b = a.read()
y = [0]*len(b)
for i in range (0,len(b)):
    asc = (ord(b[i]))
    asc = asc + len(b)
    y[i]=(chr(asc))
y = "".join(y)
f= open("ENC.txt", "w")
f.write(str(y))
print(y)
